const ACTION_TYPES = {
  ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
  GET_USER_CHATS_LIST_REQUEST: 'GET_USER_CHATS_LIST_REQUEST',
  GET_USER_CHATS_LIST_SUCESS: 'GET_USER_CHATS_LIST_SUCESS',
  GET_USER_CHATS_LIST_ERROR: 'GET_USER_CHATS_LIST_ERROR',
  GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR'
  }

  export default ACTION_TYPES;