const ACTION_TYPES = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',

  GET_USER_CHATS_LIST_REQUEST: 'GET_USER_CHATS_LIST_REQUEST',
  GET_USER_CHATS_LIST_SUCESS: 'GET_USER_CHATS_LIST_SUCESS',
  GET_USER_CHATS_LIST_ERROR: 'GET_USER_CHATS_LIST_ERROR',
  
  GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_ERROR: 'GET_USER_DATA_ERROR',
  
  GET_CURRENT_CHAT_REQUEST: 'GET_CURRENT_CHAT_REQUEST',
  GET_CURRENT_CHAT_SUCCESS: 'GET_CURRENT_CHAT_SUCCESS',
  GET_CURRENT_CHAT_ERROR: 'GET_CURRENT_CHAT_ERROR',
  
  ADD_NEW_MESSAGE_REQUEST: 'ADD_NEW_MESSAGE_REQUEST',
  ADD_NEW_MESSAGE_SUCCESS: 'ADD_NEW_MESSAGE_SUCCESS',
  ADD_NEW_MESSAGE_ERROR: 'ADD_NEW_MESSAGE_ERROR', 

  }

  export default ACTION_TYPES;