GET http://localhost:5000/api/chats/65e6df0524de2c1072ef5d9c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1OTVhNGI2ZTIwZjBiYTMyMzY5MWMiLCJlbWFpbCI6ImphbmVEZWVlb2VAcmUuZmQiLCJpYXQiOjE3MTA0OTQ4NDMsImV4cCI6MTcxMDUxNjQ0M30.zJ1IFgbGxEmREG4AQPHAttdUoESPX9stgZspbSwbUNY